name: Ejecutar Blueeyestats Lab

on:
  schedule:
    - cron: '0 21 * * *' # Se ejecuta a las 21:00 cada día
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install pandas requests nba_api openai

      - name: Ejecutar Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python bot_nba.py

      - name: Subir cambios a la Web
        run: |
          git config --global user.name "Blueeyestats Bot"
          git config --global user.email "bot@blueeyestats.com"
          git add index.html
          git commit -m "Actualización Dashboard Blueeyestats-lab" || exit 0
          git push
