name: Ejecutar Blueeyestats Lab

on:
  workflow_dispatch: # Botón manual
  schedule:
    - cron: '0 21 * * *' # Automático a las 21:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Librerías
        run: pip install pandas requests nba_api openai

      - name: Ejecutar Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python bot_nba.py

      - name: Publicar en Web
        run: |
          git config --global user.name "Blueeyestats Bot"
          git config --global user.email "bot@blueeyestats.com"
          git add index.html
          git commit -m "Update Dashboard" || exit 0
          git push
